'use strict';
const path = require('node:path');
const fs = require('node:fs');
const { chromium } = require('C:/Users/q1212/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'chrome', args: ['--enable-webgl', '--ignore-gpu-blocklist'] });
  const page = await browser.newPage({ viewport: { width: 1600, height: 1000 }, deviceScaleFactor: 1 });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
  await page.goto('http://127.0.0.1:4419/pulse/', { waitUntil: 'load', timeout: 60000 });
  await page.waitForFunction(() => window.pulseScene || !document.getElementById('fallback').hidden, { timeout: 60000 });
  await page.waitForTimeout(3500);
  await page.screenshot({ path: path.join(__dirname, 'entry-desktop.png') });
  await page.locator('#display-toggle').click();
  await page.locator('#quality').selectOption('high');
  await page.locator('#scene-only').click();
  await page.waitForTimeout(1600);
  await page.screenshot({ path: path.join(__dirname, 'scene-street.png') });
  const metrics = await page.evaluate(() => window.pulseScene?.getMetrics() || null);
  const frames = await page.evaluate(() => new Promise(resolve => { const deltas=[];let prior=performance.now(),start=prior;function sample(now){deltas.push(now-prior);prior=now;if(now-start<5000)requestAnimationFrame(sample);else{deltas.shift();deltas.sort((a,b)=>a-b);resolve({seconds:(now-start)/1000,frames:deltas.length,observedFps:deltas.length/((now-start)/1000),medianFrameMs:deltas[Math.floor(deltas.length/2)],p95FrameMs:deltas[Math.floor(deltas.length*.95)]});}}requestAnimationFrame(sample);}));
  await page.evaluate(() => window.pulseScene?.focus('overview'));
  await page.waitForTimeout(1800);
  await page.screenshot({ path: path.join(__dirname, 'scene-overview.png') });
  await page.evaluate(() => window.pulseScene?.focus('tram'));
  await page.waitForTimeout(1800);
  await page.screenshot({ path: path.join(__dirname, 'scene-tram.png') });
  await page.locator('#restore-ui').click();
  await page.locator('#display-toggle').click();
  await page.locator('#quality').selectOption('low');
  await page.locator('#motion-choice').selectOption('reduce');
  await page.locator('#scene-only').click();
  await page.waitForTimeout(1000);
  const lightMode = await page.evaluate(() => window.pulseScene?.getMetrics() || null);
  await page.screenshot({ path: path.join(__dirname, 'scene-light-mode.png') });
  if (!lightMode || lightMode.quality !== 'low' || lightMode.reflections || lightMode.silhouetteFibres || !lightMode.reducedMotion) throw new Error('Light/reduced-motion controls did not reach the renderer.');
  const evidence = { capturedAt: new Date().toISOString(), viewport: { width: 1600, height: 1000 }, metrics, frames, lightMode, errors };
  fs.writeFileSync(path.join(__dirname, 'render-evidence.json'), JSON.stringify(evidence, null, 2));
  console.log(JSON.stringify(evidence, null, 2));
  await browser.close();
})().catch(e => { console.error(e); process.exitCode = 1; });
