'use strict';
const fs=require('fs'),path=require('path');
const repo=path.resolve(__dirname,'..');
const output=process.env.SYNK_ENGINE_VIDEO_OUTPUT||'C:/Users/q1212/.codex/visualizations/2026/09/11/01a08f0d-d3c5-7c41-9c85-d69384fa2412/IP_디딤돌_준비/미팅완성본/원리영상_20260912';
const timeline=require('./src/특허원리20260912/timeline.json');
const tokens=require('../docs/디자인_토큰.json');
const color=name=>tokens.색.킷.find(c=>c.이름===name).hex;
const semantic=name=>color(tokens.색.시맨틱.라이트[name]);
const data=(file,mime)=>`data:${mime};base64,${fs.readFileSync(file).toString('base64')}`;
const font=(file,weight)=>`@font-face{font-family:'Engine SUIT';font-weight:${weight};src:url('${data(path.join(repo,'docs/브랜드_폰트/SUIT',file),'font/otf')}') format('opentype');font-display:swap}`;
const latin=`@font-face{font-family:'Inter Tight';font-weight:500;src:url('${data(path.join(repo,'docs/브랜드_폰트/InterTight/InterTight-Medium.ttf'),'font/ttf')}') format('truetype');font-display:swap}@font-face{font-family:'Inter Tight';font-weight:800;src:url('${data(path.join(repo,'docs/브랜드_폰트/InterTight/InterTight-Bold.ttf'),'font/ttf')}') format('truetype');font-display:swap}`;
const chapters=[['01','처음부터 보기'],['03','세 칸으로 나누기'],['08','같은 녹음 다시 듣기'],['09','도움 뒤의 새 말'],['11','늦게 온 사실로 수정'],['14','정리와 실제 작동']].map(([id,title])=>({id,title,start:timeline.scenes.find(s=>s.id===id).start/30}));
const time=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
const movie='펠트 엔진_한 문장이 기록되는 과정.mp4';
const html=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>말 한 번, 확인은 세 가지 · 펠트 엔진</title>
<style>${font('SUIT-Medium.otf',500)}${font('SUIT-ExtraBold.otf',800)}${latin}
:root{--paper:${semantic('바탕')};--ink:${semantic('잉크')};--muted:${semantic('보조잉크')};--oat:${color('Oat')};--stone:${color('Stone')};--coral:${semantic('신호_면')};--deep:${semantic('신호_글자_대형')};--wash:${semantic('신호_바닥')}}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:'Inter Tight','Engine SUIT',sans-serif;font-weight:500;word-break:keep-all}main{max-width:1280px;margin:0 auto;padding:38px 30px 64px}header{display:flex;gap:20px;align-items:center;justify-content:space-between;margin-bottom:32px}header img{width:170px;height:auto}header span{color:var(--muted);font-size:15px}h1{font-size:clamp(28px,3vw,42px);line-height:1.25;letter-spacing:-.05em;margin:0 0 12px;font-weight:800}.intro{color:var(--muted);font-size:17px;line-height:1.7;margin:0 0 26px}video{display:block;width:100%;aspect-ratio:16/9;background:var(--ink);border-radius:20px;border:1px solid var(--stone)}.controls{display:flex;align-items:center;gap:10px;flex-wrap:wrap;padding:18px 0;border-bottom:1px solid var(--oat)}button,select{font:inherit;color:var(--ink);background:var(--paper);border:1px solid var(--stone);padding:12px 16px;border-radius:12px;cursor:pointer}button:hover{background:var(--oat)}button:focus-visible,select:focus-visible{outline:3px solid var(--coral);outline-offset:3px}.primary{background:var(--ink);color:var(--paper);border-color:var(--ink);font-weight:800}.primary:hover{background:var(--deep)}.spacer{flex:1}#clock{font-variant-numeric:tabular-nums;font-size:15px;color:var(--muted);min-width:94px}.chapters{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:25px 0 28px}.chapter{text-align:left;min-height:85px;display:flex;align-items:center;gap:15px;border-color:var(--oat)}.chapter[aria-current=true]{border-color:var(--coral);background:var(--wash)}.chapter small{font-size:14px;color:var(--muted);min-width:38px}.chapter b{font-weight:800;font-size:16px;line-height:1.5}.takeaway{border-top:1px solid var(--oat);padding:24px 0 0;color:var(--muted);line-height:1.8;font-size:15px}.takeaway strong{color:var(--ink)}a{color:var(--deep)}footer{font-size:13px;line-height:1.7;color:var(--muted);margin-top:28px}@media(max-width:700px){main{padding:23px 16px 45px}header{margin-bottom:26px}header img{width:135px}.chapters{grid-template-columns:1fr 1fr;gap:8px}.chapter{padding:12px;gap:8px}.chapter b{font-size:14px}.controls{gap:8px}.controls button,.controls select{padding:10px 12px}.spacer{display:none}video{border-radius:12px}#clock{margin-left:auto}header span{font-size:12px}}@media(prefers-reduced-motion:no-preference){button{transition:background 140ms ease,border-color 140ms ease}}
</style><main><header><img alt="SYNK LAB" src="${data(path.join(repo,'tools/patent-studio/public/assets/logo.webp'),'image/webp')}"><span>펠트 엔진 · ${time(timeline.durationSeconds)}</span></header><h1>말 한 번, 확인은 세 가지.</h1><p class="intro">“친구를 만나서 카페에 갔어요.”<br>이 문장이 어떻게 기록되고, 어떤 이유로 판단이 달라지는지 함께 따라가요.</p>
<video id="film" controls playsinline preload="metadata" poster="${encodeURI('표지.png')}" aria-label="펠트 엔진의 작동 원리 설명 영상"><source src="${encodeURI(movie)}" type="video/mp4">영상 재생을 지원하는 브라우저에서 열어 주세요.</video>
<div class="controls"><button class="primary" id="play">영상 보기</button><button id="back">10초 뒤로</button><button id="repeat">이 장면 다시 보기</button><span class="spacer"></span><label for="rate">속도</label><select id="rate"><option value="0.75">천천히 · 0.75배</option><option value="1" selected>보통 · 1배</option><option value="1.25">빠르게 · 1.25배</option></select><span id="clock">0:00 / ${time(timeline.durationSeconds)}</span></div>
<nav class="chapters" aria-label="장면으로 이동">${chapters.map(c=>`<button class="chapter" data-start="${c.start}" aria-current="false"><small>${time(c.start)}</small><b>${c.title}</b></button>`).join('')}</nav>
<div class="takeaway"><strong>처음 소리는 보관하고 → 질문마다 따로 확인하고 → 새 사실과 관련된 판단을 고쳐요.</strong><br>영상 속 ‘기록’은 근거를 남긴다는 뜻이에요. 정답 점수나 실력 점수를 뜻하지 않아요.</div>
<footer>한국어 안내와 예시 발화는 기계 음성입니다. 마지막 화면은 로컬 작업실에서 통제 예제를 실제 실행한 녹화입니다.<br><a href="${encodeURI(movie)}" download>MP4 저장</a> · <a href="${encodeURI('자막.srt')}" download>자막 파일</a></footer></main>
<script>const v=document.getElementById('film'),play=document.getElementById('play'),chapterButtons=[...document.querySelectorAll('.chapter')];const stamps=${JSON.stringify(timeline.scenes.map(s=>s.start/30))};const fmt=s=>Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0');function current(){return stamps.filter(s=>s<=v.currentTime+.15).at(-1)||0}play.onclick=()=>v.paused?v.play().catch(()=>{}):v.pause();document.getElementById('back').onclick=()=>v.currentTime=Math.max(0,v.currentTime-10);document.getElementById('repeat').onclick=()=>{v.currentTime=current();v.play().catch(()=>{})};document.getElementById('rate').onchange=e=>v.playbackRate=Number(e.target.value);chapterButtons.forEach(b=>b.onclick=()=>{v.currentTime=Number(b.dataset.start);v.play().catch(()=>{})});function update(){play.textContent=v.paused?'영상 보기':'잠깐 멈추기';document.getElementById('clock').textContent=fmt(v.currentTime)+' / '+fmt(Number.isFinite(v.duration)?v.duration:${timeline.durationSeconds});const active=chapterButtons.filter(b=>Number(b.dataset.start)<=v.currentTime+.15).at(-1);chapterButtons.forEach(b=>b.setAttribute('aria-current',String(b===active)))}['timeupdate','play','pause','loadedmetadata','ended'].forEach(e=>v.addEventListener(e,update));update();</script></html>`;
const playable=html
  .replace('</style>','.screen{position:relative}#posterPlay{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);display:flex;gap:10px;align-items:center;padding:16px 25px;background:var(--ink);color:var(--paper);font-weight:800;box-shadow:0 0 0 1px var(--paper)}#posterPlay[hidden]{display:none}#posterPlay:hover{background:var(--deep)}</style>')
  .replace('<video id="film"','<div class="screen"><video id="film"')
  .replace('</video>','</video><button id="posterPlay" aria-label="펠트 엔진 영상 재생"><svg width="20" height="20" viewBox="0 0 24 24" aria-hidden="true"><path d="m7 4 14 8-14 8Z" fill="currentColor"/></svg>영상 보기</button></div>')
  .replace('</html>','<script>const posterPlay=document.getElementById("posterPlay");posterPlay.onclick=()=>v.play().catch(()=>{});function posterState(){posterPlay.hidden=!v.paused||v.currentTime>.1}["timeupdate","play","pause","loadedmetadata"].forEach(e=>v.addEventListener(e,posterState));posterState();</script></html>');
fs.writeFileSync(path.join(output,'펠트 엔진_영상으로 보기.html'),playable);
fs.writeFileSync(path.join(output,'먼저보기.md'),`# 펠트 엔진 원리 영상\n\n${time(timeline.durationSeconds)} · 1920×1080 · 한국어 기계 음성·자막 포함\n\n처음에는 「펠트 엔진_한 문장이 기록되는 과정.mp4」를 재생합니다. 「펠트 엔진_영상으로 보기.html」은 장면 이동, 10초 뒤로, 장면 다시 보기, 재생 속도 조절을 제공합니다. 두 파일과 표지를 같은 폴더에 두면 됩니다.\n\n${chapters.map(c=>`- ${time(c.start)} ${c.title}`).join('\n')}\n\n현재 로컬 통제 예제의 처리 원리입니다. 실제 학생의 학습 성과나 운영 제품 전체 연동을 시연한 것은 아닙니다.\n\n문장과 조건을 설명하기 위한 애니메이션 다음에, 실제 로컬 작업실의 판정 변화 녹화를 연결했습니다. 처음 소리·새 발화·판정과 이력의 구분을 유지합니다.\n`);
console.log(path.join(output,'펠트 엔진_영상으로 보기.html'));
