'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const repo = path.resolve(__dirname, '../..');
const loom = require(path.join(repo, 'tools/lib/loom.js'));
const logo = require(path.join(repo, 'tools/lib/로고정본.js'));
const t = loom.정본();
const c = t.색;
const fonts = path.join(__dirname, 'shared/fonts');
fs.mkdirSync(fonts, { recursive: true });
for (const [from, to] of [['SUIT/SUIT-Variable.woff2', 'SUIT-Variable.woff2'], ['SUIT/LICENSE_OFL.txt', 'SUIT-LICENSE.txt'], ['InterTight/InterTight-Regular.ttf', 'InterTight-Regular.ttf'], ['InterTight/InterTight-Bold.ttf', 'InterTight-Bold.ttf'], ['InterTight/OFL.txt', 'InterTight-LICENSE.txt'], ['SYNKBracket/SYNKBracket-Regular.ttf', 'SYNKBracket-Regular.ttf'], ['SYNKBracket/OFL.txt', 'SYNKBracket-LICENSE.txt']]) fs.copyFileSync(path.join(repo, 'docs/브랜드_폰트', from), path.join(fonts, to));
fs.writeFileSync(path.join(__dirname, 'shared/loom.css'), loom.css({ 지면: '웹' }));
// Loom의 바탕·부품을 소비하고 이 체험 입구의 배치만 확장한다. 색과 폰트 값은 정본에서 파생한다.
const css = `
@font-face{font-family:'SUIT Variable';src:url('./shared/fonts/SUIT-Variable.woff2') format('woff2');font-weight:100 900;font-display:swap}
@font-face{font-family:'Inter Tight';src:url('./shared/fonts/InterTight-Regular.ttf') format('truetype');font-weight:400;font-display:swap}
@font-face{font-family:'Inter Tight';src:url('./shared/fonts/InterTight-Bold.ttf') format('truetype');font-weight:700;font-display:swap}
@font-face{font-family:'SYNK Bracket';src:url('./shared/fonts/SYNKBracket-Regular.ttf') format('truetype');font-display:swap}
:root{--experience-paper:${c.Paper};--experience-ink:${c.Ink};--experience-night:${c['Ink Deep']};--experience-muted:${c.Stone};--experience-stitch:${c.Stitch};--experience-coral:${c.Coral};--experience-font:${t.서체.본문스택}}
html,body{background:var(--experience-night);color:var(--experience-paper);font-family:var(--experience-font);font-size:16px;line-height:1.6;scroll-behavior:auto}
body:before,body:after{display:none}*{box-sizing:border-box}a{color:inherit;text-decoration:none}button,a{touch-action:manipulation}a:focus-visible,button:focus-visible{outline:3px solid var(--experience-stitch);outline-offset:5px}
.home-wrap h2::before,.home-wrap h2::after,.home-wrap a::before,.home-wrap a::after{content:none!important;display:none!important}.home-wrap h2{display:block;padding:0;border:0}.home-wrap a{border-bottom:0}.home-wrap a.text-link{border-bottom:1px solid var(--experience-stitch)}
.home-wrap{max-width:1456px;margin:auto;padding:0 64px}.topline{height:104px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid ${c.Ink};gap:20px}.brand-home{display:flex;align-items:center;gap:23px}.brand-home svg{width:105px;height:auto;display:block}.topline small{font-size:12px;letter-spacing:.1em;color:var(--experience-muted)}.top-note{display:flex;gap:9px;align-items:center}.top-note:before{content:'';width:6px;height:6px;border-radius:50%;background:var(--experience-coral)}
.intro{display:flex;justify-content:space-between;align-items:flex-end;gap:40px;padding:57px 0 37px}.intro h1{font-size:clamp(30px,3.2vw,48px);line-height:1.3;letter-spacing:-.055em;font-weight:700;margin:0;color:var(--experience-paper)}.intro p{font-size:15px;line-height:1.7;color:var(--experience-muted);margin:0;max-width:330px;word-break:keep-all}.kicker{display:block;font-size:11px;font-weight:700;letter-spacing:.2em;margin-bottom:14px;color:var(--experience-muted)}
.feature{position:relative;min-height:560px;border-radius:6px;overflow:hidden;isolation:isolate;background:var(--experience-ink)}.feature>img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center;z-index:-3}.feature:before{position:absolute;inset:0;content:'';background:linear-gradient(90deg,rgba(8,6,5,.81),rgba(8,6,5,.2) 65%),linear-gradient(0deg,rgba(8,6,5,.7),transparent 60%);z-index:-2}.feature-copy{max-width:535px;padding:66px 55px 57px;min-height:560px;display:flex;flex-direction:column;align-items:flex-start;justify-content:flex-end}.episode{font-size:11px;letter-spacing:.18em;color:var(--experience-stitch);font-weight:700}.feature h2{font-size:clamp(42px,5vw,72px);font-weight:700;letter-spacing:-.065em;line-height:1.17;margin:20px 0 22px;color:var(--experience-paper)}.feature p{max-width:310px;font-size:16px;line-height:1.85;color:var(--experience-paper);word-break:keep-all;margin:0 0 29px}.cta{display:inline-flex;align-items:center;gap:26px;min-height:50px;padding:13px 20px;border-radius:4px;background:var(--experience-coral);color:var(--experience-ink);font-size:14px;font-weight:800;transition:transform 180ms ease}.cta:hover{transform:translateY(-2px)}.cta:active{transform:scale(.96)}.feature-meta{font-size:11px!important;letter-spacing:.02em;color:var(--experience-stitch)!important;margin:19px 0 0!important}.feature-label{position:absolute;right:24px;top:23px;border:1px solid rgba(251,202,171,.4);border-radius:30px;padding:6px 13px;font-size:11px;background:rgba(8,6,5,.55);color:var(--experience-paper)}
.companions{display:grid;grid-template-columns:1fr 1fr;gap:32px;padding:36px 0 52px}.companion{padding:28px 0 14px;border-top:1px solid ${c['Deep Wool']};display:grid;grid-template-columns:42px 1fr;gap:18px}.number{font-size:12px;color:var(--experience-muted);padding-top:1px;font-variant-numeric:tabular-nums}.companion h2{font-size:24px;font-weight:700;line-height:1.4;letter-spacing:-.04em;margin:14px 0 11px;color:var(--experience-paper)}.companion p{font-size:14px;color:var(--experience-muted);line-height:1.9;margin:0 0 22px;max-width:385px;word-break:keep-all}.companion .kicker{margin:0;font-size:10px;color:var(--experience-stitch);letter-spacing:.12em}.text-link{font-size:14px;min-height:44px;display:inline-flex;align-items:center;gap:26px;border-bottom:1px solid var(--experience-stitch);font-weight:600;padding-bottom:4px}.text-link:hover{color:var(--experience-stitch)}
.home-footer{padding:26px 0 32px;border-top:1px solid ${c.Ink};display:flex;justify-content:space-between;gap:30px;font-size:12px;color:var(--experience-muted)}.home-footer details{max-width:650px}.home-footer summary{cursor:pointer;min-height:35px}.home-footer p{font-size:12px;line-height:1.8;margin:7px 0;color:var(--experience-muted)}.motion-control{border:1px solid ${c['Deep Wool']};border-radius:4px;background:transparent;color:var(--experience-paper);padding:9px 13px;min-height:42px;align-self:flex-start;font-family:inherit;font-size:12px;cursor:pointer}
@media(max-width:820px){.home-wrap{padding:0 28px}.topline{height:84px}.intro{display:block;padding:38px 0 28px}.intro p{max-width:unset;margin-top:19px;font-size:14px}.feature,.feature-copy{min-height:520px}.feature-copy{padding:40px 30px}.feature-copy h2{font-size:52px}.feature>img{object-position:57% center}.companions{gap:24px}.companion{grid-template-columns:25px 1fr;gap:10px}.companion h2{font-size:21px}}
@media(max-width:540px){.home-wrap{padding:0 20px}.topline small:last-child{font-size:10px}.brand-home{gap:13px}.brand-home svg{width:86px}.brand-home small{display:none}.intro h1{font-size:32px}.intro p{max-width:290px}.feature,.feature-copy{min-height:510px}.feature-copy{padding:28px 25px}.feature h2{font-size:47px}.feature p{font-size:14px;max-width:240px}.feature:before{background:linear-gradient(0deg,rgba(8,6,5,.96),rgba(8,6,5,.28) 85%)}.feature>img{object-position:62% center}.feature-label{top:17px;right:17px;font-size:10px}.companions{grid-template-columns:1fr;gap:24px;padding:31px 0}.companion{padding-top:23px}.home-footer{display:block}.motion-control{margin-top:15px}.feature-meta{font-size:10px!important}}
@media(prefers-reduced-motion:reduce){.cta{transition:none}.cta:hover{transform:none}}
html[data-synk-motion=reduce] .cta{transition:none}html[data-synk-motion=reduce] .cta:hover{transform:none}
`;
fs.writeFileSync(path.join(__dirname, 'hub.css'), css);
const markup = `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="${c['Ink Deep']}"><title>SYNK — 새로운 경험의 첫 장</title><link rel="stylesheet" href="./shared/loom.css"><link rel="stylesheet" href="./hub.css"><link rel="stylesheet" href="./accessibility/a11y.css"></head><body>
<a class="synk-skip-link" href="#main">본문으로 건너뛰기</a>
<div class="home-wrap"><header class="topline"><a class="brand-home" href="./" aria-label="SYNK 경험 첫 화면">${logo.워드마크({ 판: '다크', 표현: '평면', 신호: 'k', 색갈래: '단색' })}<small>FIRST EXPERIENCES</small></a><small class="top-note">직접 해보는 첫 결과물</small></header>
<main id="main" tabindex="-1"><div class="intro"><div><span class="kicker">SYNK · SEPTEMBER 2026</span><h1>새로운 경험의 첫 장.</h1></div><p>배운 것을 써보고, 함께 이야기를 완성하고,<br>서로 다른 방식으로 같은 장면을 만납니다.</p></div>
<article class="feature" aria-labelledby="story-title"><img src="./pulse/assets/felt-city.png" alt="펠트 해안 도시의 밤. 굽은 전차 선로 오른쪽에 전차와 방송국이 있고, 왼쪽 항구 너머로 등대가 보인다."><span class="feature-label">펠트 도시의 미술 기준 장면</span><div class="feature-copy"><span class="episode">PULSE ORIGINAL · FIRST CHAPTER</span><h2 id="story-title">마지막 불빛</h2><p>도시에 남은 불빛은 하나.<br>당신이 발견한 단서와 친구의 이야기가<br>이 밤의 끝을 바꿉니다.</p><a class="cta" href="./pulse/">이야기 들어가기 <span aria-hidden="true">↗</span></a><p class="feature-meta">친구와 2–4인 · 한 기기에서 두 역할 체험 가능</p></div></article>
<div class="companions"><article class="companion" aria-labelledby="rehearsal-title"><span class="number" aria-hidden="true">01</span><div><span class="kicker">LAB · SHIFT / 실전 리허설</span><h2 id="rehearsal-title">고객의 요구가 바뀐다면.</h2><p>질문하고 제안하고, 달라진 조건에 다시 답합니다. 처음 생각과 수정 이유가 나만의 실습 기록으로 남습니다.</p><a class="text-link" href="./rehearsal/">첫 의뢰 만나기 <span aria-hidden="true">↗</span></a></div></article>
<article class="companion" aria-labelledby="access-title"><span class="number" aria-hidden="true">03</span><div><span class="kicker">SYNK COMMON / 접근성 감상실</span><h2 id="access-title">같은 장면, 여러 가지 길.</h2><p>장면을 글로 살펴보고, 움직임을 조절하고, 키보드로 이동합니다. 감상에 필요한 길을 하나씩 넓혀 갑니다.</p><a class="text-link" href="./accessibility/">다른 방식으로 감상하기 <span aria-hidden="true">↗</span></a></div></article></div></main>
<footer class="home-footer"><details><summary>이번 첫 체험에 관하여</summary><p>세 결과물은 직접 사용해 보는 첫 구현입니다. 실제 수업의 효과, 친구 모임의 재미와 재구매, 전문 접근성 검수는 앞으로 확인할 부분입니다. 작품의 미술 기준 이미지와 실시간 3D 장면은 별도의 결과물입니다.</p><p>리허설 입력은 이 브라우저에 저장됩니다. 이야기 방은 실행 중인 체험 서버에만 남고 서버를 닫으면 사라집니다. 실제 고객·학생의 식별 정보를 입력하지 않아도 체험할 수 있습니다.</p></details><button type="button" class="motion-control" id="motion-toggle" aria-pressed="false">움직임 줄이기</button></footer></div><script src="./accessibility/a11y.js"></script><script src="./hub.js"></script></body></html>`;
fs.writeFileSync(path.join(__dirname, 'index.html'), markup);
fs.mkdirSync(path.join(__dirname, 'qa'), { recursive: true });
const hash = file => crypto.createHash('sha256').update(fs.readFileSync(path.join(repo, file))).digest('hex');
fs.writeFileSync(path.join(__dirname, 'qa/hub-sources.json'), JSON.stringify({ generated: new Date().toISOString(), sources: Object.fromEntries(['DESIGN.md', 'docs/디자인_토큰.json', 'tools/lib/loom.js', 'tools/lib/로고정본.js', 'docs/AI_운영원칙.md'].map(file => [file, hash(file)])) }, null, 2));
console.log('SYNK 경험 입구 생성 완료');
