'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root='C:/Users/q1212/.codex/visualizations/2026/09/11/01a08f0d-d3c5-7c41-9c85-d69384fa2412/IP_디딤돌_준비/미팅완성본';
const packet=path.join(root,'현재_미팅본_20260912'),out=path.join(root,'발전구현_0.5_20260912');
for(const ext of ['html','pdf'])fs.copyFileSync(path.join(out,'SYNK_CORE_등록준비_발전구현_0.5.'+ext),path.join(packet,'07_발전구현.'+ext));
const entry=path.join(packet,'00_여기서시작.html');let html=fs.readFileSync(entry,'utf8');
html=html.replace(/<section class="action" data-advance-implementation>[\s\S]*?<\/section>/,'');
const action='<section class="action" data-advance-implementation><div><h2>가장 먼저 · Core 0.5 발전 구현</h2><p>새로 작동하는 시간 범위·복수 보류 확인을 11쪽에 정리했습니다. 실제 연결·데이터 계약·계산 규모·비교 근거·청구 후보와 5분 시연 순서를 확인하세요.</p></div><div class="buttons"><a class="button primary" href="07_발전구현.html" target="_blank">발전 구현 열기</a><a class="button" href="07_발전구현.pdf" target="_blank">인쇄 PDF</a></div></section>';
html=html.replace('<section class="action" data-registration-strategy>',action+'<section class="action" data-registration-strategy>');
html=html.replace('가장 먼저 · 등록특허 1건 전략','함께 볼 자료 · 등록특허 1건 전략').replace('새 전략 열기','등록 전략 열기');fs.writeFileSync(entry,html);
fs.writeFileSync(path.join(root,'00_현재본_여기부터.md'),'# 현재 특허 미팅본 · Core 0.5 발전 구현\n\n[현재 미팅 시작 화면](현재_미팅본_20260912/00_여기서시작.html)에서 **발전 구현 열기**를 누릅니다.\n\n11쪽 현재 구현 → 실제 작업실의 시간·복수 보류 예제 → 기존16쪽 등록 전략 순서입니다.\n\n목표는 실제 기술의 등록특허1건으로 기업 신뢰를 확보하는 것입니다. 기술 중심은 SYNK Core, 표현은 Loom, 통합 제품은 Atlas입니다. 시간·관측 기능과 시연은 로컬0.5에 구현됐습니다. 선행 전체대조·최종출원·등록은 완료되지 않았습니다. 기존0.4 증거는 당시소스로 보존합니다.\n');
fs.writeFileSync(path.join(packet,'00_미팅진행가이드.md'),'# Core 0.5 · 미팅 진행\n\n1. 07_발전구현.html/PDF를 열어1~2쪽으로 원리를 설명합니다.\n2. 06_작업실_실행.cmd 또는 저장소 start.cmd로 작업실을 엽니다. 현재 엔진0.5이며 이전 시연은 읽기전용입니다. 새 예제로 시작하세요.\n3. 시간이 애매한 예제 → 발화 후 확인 → 새 시간 예제 → 발화 전 확인. 조사만 보류/반영/제외되고 전사·독립 과거형은 유지됩니다.\n4. 여러 확인 예제 → 전사·문항 확인 → 시간이 남는 것을 확인 → 시간 확인. 조건부 계획은 실제 관측 전 승인하지 않습니다.\n5. 저장 기록 재현 확인/기록 내려받기로 실제 사건·판정·원장을 보여줍니다. 새 시연은 합성 사건으로 인터넷·학생·마이크를 사용하지 않습니다.\n6. 11쪽의 요건·9쪽의 구성 후보와 05_등록우선전략을 함께 보고, 가까운 문헌에 대한 최종청구 한정을 논의합니다.\n\n엔진 전체의 신규성을 주장하지 않습니다. 시간 구간이나 일반 계획법은 알려진 구성입니다. 구체적으로 연결한 처리에서 남는 차이와 결합 동기를 검토받습니다.\n');
const hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const mp=path.join(packet,'파일지문.json');let manifest=JSON.parse(fs.readFileSync(mp,'utf8'));
const files=fs.readdirSync(packet,{recursive:true}).filter(n=>fs.statSync(path.join(packet,n)).isFile()&&n!=='파일지문.json');
manifest={...manifest,generatedAt:new Date().toISOString(),currentCore:'0.5.0',primary:'07_발전구현.html',files:files.map(n=>({path:n,bytes:fs.statSync(path.join(packet,n)).size,sha256:hash(path.join(packet,n))}))};fs.writeFileSync(mp,JSON.stringify(manifest,null,2));
for(const name of ['GATE.md','README.md','B_planning.md'])fs.copyFileSync(path.join(__dirname,name),path.join(out,name));
fs.cpSync(path.join(__dirname,'qa'),path.join(out,'작동검증'),{recursive:true});
const outManifest=JSON.parse(fs.readFileSync(path.join(out,'파일지문.json'),'utf8'));outManifest.files=fs.readdirSync(out,{recursive:true}).filter(n=>fs.statSync(path.join(out,n)).isFile()&&n!=='파일지문.json').map(n=>({path:n,bytes:fs.statSync(path.join(out,n)).size,sha256:hash(path.join(out,n))}));fs.writeFileSync(path.join(out,'파일지문.json'),JSON.stringify(outManifest,null,2));
console.log(JSON.stringify({entry,primary:manifest.primary,files:files.length}));
